/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;
import java.sql.*;
import javax.swing.JOptionPane;
import Connection.javaconnect;
import java.text.SimpleDateFormat;
import javax.swing.*;
import javax.swing.table.*;

/**
 *
 * @author Puskar
 */
public class issuebook extends javax.swing.JFrame {

    /**
     * Creates new form issuebook
     */
    public issuebook() {
        initComponents();
        setLocationRelativeTo(null);
        
    }
Connection con;
ResultSet rs;
PreparedStatement pst;
Statement stmt;
int count=0;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        t4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        t6 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        t5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        slno = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        rdate = new com.toedter.calendar.JDateChooser();
        idate = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon 1/home2.jpeg"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 39, 38));

        jLabel1.setText("User ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 87, 114, 17));
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 81, 174, -1));

        jLabel2.setText("Book Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 118, 114, -1));
        getContentPane().add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 158, 174, -1));

        b1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        b1.setText("Verify");
        b1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, -1, -1));

        b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon 1/search.png"))); // NOI18N
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, -1, 20));

        jLabel3.setText("Author");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 204, 114, -1));
        getContentPane().add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 198, 174, -1));

        jLabel4.setText("Book ID");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 164, 114, -1));
        getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 118, 174, 23));

        jLabel5.setText("Date of Edition");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 290, 114, 17));
        getContentPane().add(t6, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 284, 174, -1));

        jLabel6.setText("Publisher");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 249, 114, 17));
        getContentPane().add(t5, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 243, 174, -1));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel7.setText("Serial No. ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 34, -1, -1));
        getContentPane().add(slno, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 33, -1, -1));

        jLabel8.setText("Date of Issue");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 331, 99, 17));

        jLabel9.setText("Date of Issue");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 374, 99, 17));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book ID", "Book Title", "Author", "Publication", "Edition"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        table.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tableComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, 530, 380));

        b3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        b3.setText("ISSUE");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        getContentPane().add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, -1, -1));

        b4.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        b4.setText("CLEAR ALL RECORDS");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        getContentPane().add(b4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 420, -1, -1));
        getContentPane().add(rdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 180, -1));
        getContentPane().add(idate, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 180, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        String userid=t1.getText();
        String sql="select * from user_info where uname = '"+userid+"'";
        DefaultTableModel ob=(DefaultTableModel)table.getModel();
        try{
            con=javaconnect.getCon();
            stmt=con.createStatement();
            rs=stmt.executeQuery(sql);
            
            while(rs.next()){
                JOptionPane.showMessageDialog(null,"Verified!");
                idate.setEnabled(true);
                rdate.setEnabled(true);
            }
            con.close();
            stmt.close();
            rs.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Error occurred");
        }// TODO add your handling code here:
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        String keyword=t2.getText();
        String sql="select * from newbook where name like '"+keyword+"%'";
        DefaultTableModel ob=(DefaultTableModel)table.getModel();
        try{
            con=javaconnect.getCon();
            stmt=con.createStatement();
            rs=stmt.executeQuery(sql);
            for(;count>0;count--)
            ob.removeRow(0);
            while(rs.next())
            {
                String bookid, title, author, publication,edition;
                bookid=rs.getString("bookid");
                title=rs.getString("name");
                author=rs.getString("author");
                publication=rs.getString("publication");
                edition=rs.getString("edition");
                String x[]={bookid,title,author,publication,edition};
                ob.addRow(x);
                count++;
                 
            }
           
            con.close();
            stmt.close();
            rs.close();
        }
        catch(Exception e)
        {}// TODO add your handling code here:
    }//GEN-LAST:event_b2ActionPerformed

    private void tableComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tableComponentShown

        // TODO add your handling code here:
    }//GEN-LAST:event_tableComponentShown

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        String sql="select * from newbook order by bookid asc";
        try{
            con=javaconnect.getCon();
            stmt=con.createStatement();
        rs=stmt.executeQuery(sql);
        while(rs.next())
        {
           String bookid, title, author, publication,edition;
           bookid=rs.getString("bookid");
           title=rs.getString("name");
           author=rs.getString("author");
           publication=rs.getString("publication");
           edition=rs.getString("edition");
           String x[]={bookid,title,author,publication,edition};
           DefaultTableModel ob=(DefaultTableModel)table.getModel();
           ob.addRow(x);
           count++;
        }  
        //System.out.print(count);
        con.close();
        stmt.close();
        rs.close();
        }
        catch(Exception e)
        {}// TODO add your handling code here:
    }//GEN-LAST:event_formComponentShown

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        int rowselected = table.getSelectedRow();
        String bookid, title, author, publication,edition;
        bookid=(String)table.getValueAt(rowselected,0);
        title=(String)table.getValueAt(rowselected,1);
        author=(String)table.getValueAt(rowselected,2);
        publication=(String)table.getValueAt(rowselected,3);
        edition=(String)table.getValueAt(rowselected, 4);
        t3.setText(bookid);
            t2.setText(title);
            t4.setText(author);
            t5.setText(publication);
            t6.setText(edition);
    }//GEN-LAST:event_tableMouseClicked

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        DefaultTableModel ob=(DefaultTableModel)table.getModel();
        for(;count>0;count--)
            ob.removeRow(0);// TODO add your handling code here:
    }//GEN-LAST:event_b4ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        
        String userid = t1.getText();
        String bookid = t3.getText();
        String name = t2.getText();
        String author = t4.getText();
        String publication = t5.getText();
        String edition=t6.getText();
        
        SimpleDateFormat dFormat = new SimpleDateFormat("yyyy-MM-dd");
        
        String issuedate=dFormat.format(idate.getDate());
        String returndate=dFormat.format(rdate.getDate());
        int serialno=(Integer)slno.getValue();
        String status="NO";
        try {
            con = javaconnect.getCon();
            String sql = "insert into issuebook values ('" +serialno+ "','" +bookid+"','"+ userid + "','" + name + "','" +issuedate+"','" +returndate+"','" + author + "','" + publication + "','"+edition+"','"+status+"')";
            if (!bookid.isEmpty() && !name.isEmpty() && !author.isEmpty() && !publication.isEmpty() && !userid.isEmpty() && !returndate.isEmpty() && !issuedate.isEmpty()) 
            {
                        stmt = con.createStatement();
                        stmt.executeUpdate(sql);
                        JOptionPane.showMessageDialog(rootPane, "Book Issued successfully!");
                        t2.setText("");
                        t3.setText("");
                        t4.setText("");
                        t5.setText("");
                        t6.setText("");
                     
                }
            else
                JOptionPane.showMessageDialog(rootPane, "Lack of information");
        }
        catch (Exception e) {

            JOptionPane.showMessageDialog(rootPane, "Error occurred! Try again!");// TODO add your handling code here:
            System.out.print(e);
    }//GEN-LAST:event_b3ActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(issuebook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(issuebook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(issuebook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(issuebook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new issuebook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private com.toedter.calendar.JDateChooser idate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser rdate;
    private javax.swing.JSpinner slno;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
