/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;
import java.sql.*;
import javax.swing.JOptionPane;
import Connection.javaconnect;
import javax.swing.*;
import javax.swing.table.*;

/**
 *
 * @author Puskar
 */
public class userHome extends javax.swing.JFrame {

    /**
     * Creates new form userHome
     */
    public userHome() {
        initComponents();
        setLocationRelativeTo(null);
    }
Connection con;
ResultSet rs;
PreparedStatement pst;
Statement stmt;
int count=0;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        lang = new javax.swing.JComboBox<>();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        b1 = new javax.swing.JButton();
        cb1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book ID", "Book Title", "Author", "Publication", "Genre", "Pages", "Rating", "Price/ Kindle Price", "Date of Edition"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        table.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tableComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 367, 862, 380));

        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Action & adventure");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 264, -1, -1));

        jCheckBox2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jCheckBox2.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox2.setText("Fiction");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 264, -1, -1));

        jCheckBox3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jCheckBox3.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox3.setText("Self Help");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 292, -1, -1));

        jCheckBox4.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jCheckBox4.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox4.setText("Mystery");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 298, -1, -1));

        jCheckBox5.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jCheckBox5.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox5.setText("Humor");
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 326, -1, -1));

        jCheckBox6.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jCheckBox6.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox6.setText("Horror");
        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 326, -1, -1));

        jCheckBox7.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jCheckBox7.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox7.setText("Romance");
        jCheckBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox7ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 354, -1, -1));

        jCheckBox8.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jCheckBox8.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox8.setText("Historical fiction");
        jCheckBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox8ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 354, -1, -1));

        jCheckBox9.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jCheckBox9.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox9.setText("Thriller & suspense");
        jCheckBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox9ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 382, -1, -1));

        jCheckBox10.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jCheckBox10.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox10.setText("Guide/ How to");
        jCheckBox10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox10ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 382, -1, -1));

        jCheckBox11.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jCheckBox11.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox11.setText("Religion & spirituality");
        jCheckBox11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox11ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox11, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 410, -1, -1));

        jCheckBox12.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jCheckBox12.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox12.setText("Education");
        jCheckBox12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox12ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, -1, -1));

        jCheckBox13.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jCheckBox13.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox13.setText("Culture");
        jCheckBox13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox13ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox13, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 438, -1, -1));

        jCheckBox14.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jCheckBox14.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox14.setText("Children's");
        jCheckBox14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox14ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox14, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 464, -1, -1));

        jCheckBox15.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jCheckBox15.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox15.setText("Biography");
        jCheckBox15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox15ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox15, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 438, -1, -1));

        jCheckBox16.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jCheckBox16.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox16.setText("Travel");
        jCheckBox16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox16ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox16, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 464, -1, -1));

        lang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "English", "Sanskrit", "Hindi", "Bengali", "Gujarati", "Marathi", "Latin", "Spanish", "French", "Greek", "Hebrew", "Tamil", "Urdu", "Telegu" }));
        lang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                langActionPerformed(evt);
            }
        });
        getContentPane().add(lang, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 264, -1, -1));

        t1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 63, 142, 32));

        t2.setForeground(new java.awt.Color(102, 102, 102));
        t2.setText("Search by book or author name");
        t2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                t2MouseEntered(evt);
            }
        });
        getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 94, 478, 30));

        b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon 1/search.png"))); // NOI18N
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(962, 94, -1, -1));

        cb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Want to read", "Have read", "Currently reading" }));
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });
        getContentPane().add(cb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 90, 112, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("a book from the table");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 60, -1, -1));

        jLabel2.setText("Choose after selecting");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 40, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 153, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jButton1.setText("YOUR DASHBOARD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 600, 240, 31));

        jRadioButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButton2.setText("ALPHABETIC ORDER");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 310, -1, -1));

        jRadioButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButton1.setText("NEWEST FIRST");
        jRadioButton1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton1ItemStateChanged(evt);
            }
        });
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 310, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon 1/userhomebg.jpeg"))); // NOI18N
        jLabel4.setMaximumSize(new java.awt.Dimension(1300, 800));
        jLabel4.setMinimumSize(new java.awt.Dimension(1300, 800));
        jLabel4.setPreferredSize(new java.awt.Dimension(1300, 800));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -60, 1400, 890));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
        String sql="select * from newbook where genre='Horror'";
        DefaultTableModel ob=(DefaultTableModel)table.getModel();
        try{
            con=javaconnect.getCon();
            stmt=con.createStatement();
        rs=stmt.executeQuery(sql);
        for(;count>0;count--)
            ob.removeRow(0);      
        while(rs.next())
        {
           String bookid, title, author, publication, pages, rating, price, edition, genre;
           bookid=rs.getString("bookid");
           title=rs.getString("name");
           author=rs.getString("author");
           publication=rs.getString("publication");
           pages=rs.getString("pages");
           rating=rs.getString("rating");
           edition=rs.getString("edition");
           price=rs.getString("price");
           genre=rs.getString("genre");
           String x[]={bookid,title,author,publication,genre,pages,rating,price,edition};
           ob.addRow(x);
           count++;
        }  
        con.close();
        stmt.close();
        rs.close();
        }
        catch(Exception e)
        {}
    }//GEN-LAST:event_jCheckBox6ActionPerformed

    private void jCheckBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox7ActionPerformed
        String sql="select * from newbook where genre='Romance'";
        DefaultTableModel ob=(DefaultTableModel)table.getModel();
        try{
            con=javaconnect.getCon();
            stmt=con.createStatement();
        rs=stmt.executeQuery(sql);
        for(;count>0;count--)
            ob.removeRow(0);      
        while(rs.next())
        {
           String bookid, title, author, publication, pages, rating, price, edition, genre;
           bookid=rs.getString("bookid");
           title=rs.getString("name");
           author=rs.getString("author");
           publication=rs.getString("publication");
           pages=rs.getString("pages");
           rating=rs.getString("rating");
           edition=rs.getString("edition");
           price=rs.getString("price");
           genre=rs.getString("genre");
           String x[]={bookid,title,author,publication,genre,pages,rating,price,edition};
           ob.addRow(x);
           count++;
        }  
        con.close();
        stmt.close();
        rs.close();
        }
        catch(Exception e)
        {}
    }//GEN-LAST:event_jCheckBox7ActionPerformed

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb1ActionPerformed

    private void t2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_t2MouseEntered

    private void t2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t2MouseClicked
        t2.setText("");// TODO add your handling code here:
        t2.setForeground(new java.awt.Color(0,0,0));
        t2.setFont(new java.awt.Font("Segoe UI", 0, 13));
    }//GEN-LAST:event_t2MouseClicked

    private void jCheckBox11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox11ActionPerformed
        String sql="select * from newbook where genre='Religion & Spirituality'";
        DefaultTableModel ob=(DefaultTableModel)table.getModel();
        try{
            con=javaconnect.getCon();
            stmt=con.createStatement();
        rs=stmt.executeQuery(sql);
        for(;count>0;count--)
            ob.removeRow(0);      
        while(rs.next())
        {
           String bookid, title, author, publication, pages, rating, price, edition, genre;
           bookid=rs.getString("bookid");
           title=rs.getString("name");
           author=rs.getString("author");
           publication=rs.getString("publication");
           pages=rs.getString("pages");
           rating=rs.getString("rating");
           edition=rs.getString("edition");
           price=rs.getString("price");
           genre=rs.getString("genre");
           String x[]={bookid,title,author,publication,genre,pages,rating,price,edition};
           ob.addRow(x);
           count++;
        }  
        con.close();
        stmt.close();
        rs.close();
        }
        catch(Exception e)
        {}
    }//GEN-LAST:event_jCheckBox11ActionPerformed

    private void tableComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tableComponentShown
        table.setRowHeight(20);

// TODO add your handling code here:
    }//GEN-LAST:event_tableComponentShown

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        String sql="select * from newbook order by bookid asc";
        try{
            con=javaconnect.getCon();
            stmt=con.createStatement();
        rs=stmt.executeQuery(sql);
        while(rs.next())
        {
           String bookid, title, author, publication, pages, rating, price, edition, genre;
           bookid=rs.getString("bookid");
           title=rs.getString("name");
           author=rs.getString("author");
           publication=rs.getString("publication");
           pages=rs.getString("pages");
           rating=rs.getString("rating");
           edition=rs.getString("edition");
           price=rs.getString("price");
           genre=rs.getString("genre");
           String x[]={bookid,title,author,publication,genre,pages,rating,price,edition};
           DefaultTableModel ob=(DefaultTableModel)table.getModel();
           ob.addRow(x);
           count++;
        }  
        //System.out.print(count);
        con.close();
        stmt.close();
        rs.close();
        }
        catch(Exception e)
        {}
// TODO add your handling code here:
    }//GEN-LAST:event_formComponentShown

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        String sql="select * from newbook where genre='Action & adventure'";
        DefaultTableModel ob=(DefaultTableModel)table.getModel();
        try{
            con=javaconnect.getCon();
            stmt=con.createStatement();
        rs=stmt.executeQuery(sql);
        for(;count>0;count--)
            ob.removeRow(0);      
        while(rs.next())
        {
           String bookid, title, author, publication, pages, rating, price, edition, genre;
           bookid=rs.getString("bookid");
           title=rs.getString("name");
           author=rs.getString("author");
           publication=rs.getString("publication");
           pages=rs.getString("pages");
           rating=rs.getString("rating");
           edition=rs.getString("edition");
           price=rs.getString("price");
           genre=rs.getString("genre");
           String x[]={bookid,title,author,publication,genre,pages,rating,price,edition};
           ob.addRow(x);
           count++;
        }  
        con.close();
        stmt.close();
        rs.close();
        }
        catch(Exception e)
        {}// TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dashboard ob=new dashboard();
        String uname = jLabel3.getText();
        ob.jLabel3.setText(uname);
        this.hide();
        ob.show();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        String sql="select * from newbook where genre='Fiction'";
        DefaultTableModel ob=(DefaultTableModel)table.getModel();
        try{
            con=javaconnect.getCon();
            stmt=con.createStatement();
        rs=stmt.executeQuery(sql);
        for(;count>0;count--)
            ob.removeRow(0);      
        while(rs.next())
        {
           String bookid, title, author, publication, pages, rating, price, edition, genre;
           bookid=rs.getString("bookid");
           title=rs.getString("name");
           author=rs.getString("author");
           publication=rs.getString("publication");
           pages=rs.getString("pages");
           rating=rs.getString("rating");
           edition=rs.getString("edition");
           price=rs.getString("price");
           genre=rs.getString("genre");
           String x[]={bookid,title,author,publication,genre,pages,rating,price,edition};
           ob.addRow(x);
           count++;
        }  
        con.close();
        stmt.close();
        rs.close();
        }
        catch(Exception e)
        {}
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        String sql="select * from newbook where genre='Self Help'";
        DefaultTableModel ob=(DefaultTableModel)table.getModel();
        try{
            con=javaconnect.getCon();
            stmt=con.createStatement();
        rs=stmt.executeQuery(sql);
        for(;count>0;count--)
            ob.removeRow(0);      
        while(rs.next())
        {
           String bookid, title, author, publication, pages, rating, price, edition, genre;
           bookid=rs.getString("bookid");
           title=rs.getString("name");
           author=rs.getString("author");
           publication=rs.getString("publication");
           pages=rs.getString("pages");
           rating=rs.getString("rating");
           edition=rs.getString("edition");
           price=rs.getString("price");
           genre=rs.getString("genre");
           String x[]={bookid,title,author,publication,genre,pages,rating,price,edition};
           ob.addRow(x);
           count++;
        }  
        con.close();
        stmt.close();
        rs.close();
        }
        catch(Exception e)
        {}
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        String sql="select * from newbook where genre='Mystery'";
        DefaultTableModel ob=(DefaultTableModel)table.getModel();
        try{
            con=javaconnect.getCon();
            stmt=con.createStatement();
        rs=stmt.executeQuery(sql);
        for(;count>0;count--)
            ob.removeRow(0);      
        while(rs.next())
        {
           String bookid, title, author, publication, pages, rating, price, edition, genre;
           bookid=rs.getString("bookid");
           title=rs.getString("name");
           author=rs.getString("author");
           publication=rs.getString("publication");
           pages=rs.getString("pages");
           rating=rs.getString("rating");
           edition=rs.getString("edition");
           price=rs.getString("price");
           genre=rs.getString("genre");
           String x[]={bookid,title,author,publication,genre,pages,rating,price,edition};
           ob.addRow(x);
           count++;
        }  
        con.close();
        stmt.close();
        rs.close();
        }
        catch(Exception e)
        {}
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        String sql="select * from newbook where genre='Humor'";
        DefaultTableModel ob=(DefaultTableModel)table.getModel();
        try{
            con=javaconnect.getCon();
            stmt=con.createStatement();
        rs=stmt.executeQuery(sql);
        for(;count>0;count--)
            ob.removeRow(0);      
        while(rs.next())
        {
           String bookid, title, author, publication, pages, rating, price, edition, genre;
           bookid=rs.getString("bookid");
           title=rs.getString("name");
           author=rs.getString("author");
           publication=rs.getString("publication");
           pages=rs.getString("pages");
           rating=rs.getString("rating");
           edition=rs.getString("edition");
           price=rs.getString("price");
           genre=rs.getString("genre");
           String x[]={bookid,title,author,publication,genre,pages,rating,price,edition};
           ob.addRow(x);
           count++;
        }  
        con.close();
        stmt.close();
        rs.close();
        }
        catch(Exception e)
        {}
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jCheckBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox8ActionPerformed
        String sql="select * from newbook where genre='Historical fiction'";
        DefaultTableModel ob=(DefaultTableModel)table.getModel();
        try{
            con=javaconnect.getCon();
            stmt=con.createStatement();
        rs=stmt.executeQuery(sql);
        for(;count>0;count--)
            ob.removeRow(0);      
        while(rs.next())
        {
           String bookid, title, author, publication, pages, rating, price, edition, genre;
           bookid=rs.getString("bookid");
           title=rs.getString("name");
           author=rs.getString("author");
           publication=rs.getString("publication");
           pages=rs.getString("pages");
           rating=rs.getString("rating");
           edition=rs.getString("edition");
           price=rs.getString("price");
           genre=rs.getString("genre");
           String x[]={bookid,title,author,publication,genre,pages,rating,price,edition};
           ob.addRow(x);
           count++;
        }  
        con.close();
        stmt.close();
        rs.close();
        }
        catch(Exception e)
        {
            System.out.print(e);
        }
    }//GEN-LAST:event_jCheckBox8ActionPerformed

    private void jCheckBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox9ActionPerformed
        String sql="select * from newbook where genre='Thriller & Suspense'";
        DefaultTableModel ob=(DefaultTableModel)table.getModel();
        try{
            con=javaconnect.getCon();
            stmt=con.createStatement();
        rs=stmt.executeQuery(sql);
        for(;count>0;count--)
            ob.removeRow(0);      
        while(rs.next())
        {
           String bookid, title, author, publication, pages, rating, price, edition, genre;
           bookid=rs.getString("bookid");
           title=rs.getString("name");
           author=rs.getString("author");
           publication=rs.getString("publication");
           pages=rs.getString("pages");
           rating=rs.getString("rating");
           edition=rs.getString("edition");
           price=rs.getString("price");
           genre=rs.getString("genre");
           String x[]={bookid,title,author,publication,genre,pages,rating,price,edition};
           ob.addRow(x);
           count++;
        }  
        con.close();
        stmt.close();
        rs.close();
        }
        catch(Exception e)
        {}
    }//GEN-LAST:event_jCheckBox9ActionPerformed

    private void jCheckBox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox10ActionPerformed
        String sql="select * from newbook where genre='Guide/ How-to'";
        DefaultTableModel ob=(DefaultTableModel)table.getModel();
        try{
            con=javaconnect.getCon();
            stmt=con.createStatement();
        rs=stmt.executeQuery(sql);
        for(;count>0;count--)
            ob.removeRow(0);      
        while(rs.next())
        {
           String bookid, title, author, publication, pages, rating, price, edition, genre;
           bookid=rs.getString("bookid");
           title=rs.getString("name");
           author=rs.getString("author");
           publication=rs.getString("publication");
           pages=rs.getString("pages");
           rating=rs.getString("rating");
           edition=rs.getString("edition");
           price=rs.getString("price");
           genre=rs.getString("genre");
           String x[]={bookid,title,author,publication,genre,pages,rating,price,edition};
           ob.addRow(x);
           count++;
        }  
        con.close();
        stmt.close();
        rs.close();
        }
        catch(Exception e)
        {}
    }//GEN-LAST:event_jCheckBox10ActionPerformed

    private void jCheckBox12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox12ActionPerformed
        String sql="select * from newbook where genre='Education'";
        DefaultTableModel ob=(DefaultTableModel)table.getModel();
        try{
            con=javaconnect.getCon();
            stmt=con.createStatement();
        rs=stmt.executeQuery(sql);
        for(;count>0;count--)
            ob.removeRow(0);      
        while(rs.next())
        {
           String bookid, title, author, publication, pages, rating, price, edition, genre;
           bookid=rs.getString("bookid");
           title=rs.getString("name");
           author=rs.getString("author");
           publication=rs.getString("publication");
           pages=rs.getString("pages");
           rating=rs.getString("rating");
           edition=rs.getString("edition");
           price=rs.getString("price");
           genre=rs.getString("genre");
           String x[]={bookid,title,author,publication,genre,pages,rating,price,edition};
           ob.addRow(x);
           count++;
        }  
        con.close();
        stmt.close();
        rs.close();
        }
        catch(Exception e)
        {}
    }//GEN-LAST:event_jCheckBox12ActionPerformed

    private void jCheckBox15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox15ActionPerformed
        String sql="select * from newbook where genre='Biography'";
        DefaultTableModel ob=(DefaultTableModel)table.getModel();
        try{
            con=javaconnect.getCon();
            stmt=con.createStatement();
        rs=stmt.executeQuery(sql);
        for(;count>0;count--)
            ob.removeRow(0);      
        while(rs.next())
        {
           String bookid, title, author, publication, pages, rating, price, edition, genre;
           bookid=rs.getString("bookid");
           title=rs.getString("name");
           author=rs.getString("author");
           publication=rs.getString("publication");
           pages=rs.getString("pages");
           rating=rs.getString("rating");
           edition=rs.getString("edition");
           price=rs.getString("price");
           genre=rs.getString("genre");
           String x[]={bookid,title,author,publication,genre,pages,rating,price,edition};
           ob.addRow(x);
           count++;
        }  
        con.close();
        stmt.close();
        rs.close();
        }
        catch(Exception e)
        {}
    }//GEN-LAST:event_jCheckBox15ActionPerformed

    private void jCheckBox13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox13ActionPerformed
        String sql="select * from newbook where genre='Culture'";
        DefaultTableModel ob=(DefaultTableModel)table.getModel();
        try{
            con=javaconnect.getCon();
            stmt=con.createStatement();
        rs=stmt.executeQuery(sql);
        for(;count>0;count--)
            ob.removeRow(0);      
        while(rs.next())
        {
           String bookid, title, author, publication, pages, rating, price, edition, genre;
           bookid=rs.getString("bookid");
           title=rs.getString("name");
           author=rs.getString("author");
           publication=rs.getString("publication");
           pages=rs.getString("pages");
           rating=rs.getString("rating");
           edition=rs.getString("edition");
           price=rs.getString("price");
           genre=rs.getString("genre");
           String x[]={bookid,title,author,publication,genre,pages,rating,price,edition};
           ob.addRow(x);
           count++;
        }  
        con.close();
        stmt.close();
        rs.close();
        }
        catch(Exception e)
        {}
    }//GEN-LAST:event_jCheckBox13ActionPerformed

    private void jCheckBox16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox16ActionPerformed
        String sql="select * from newbook where genre='Travel'";
        DefaultTableModel ob=(DefaultTableModel)table.getModel();
        try{
            con=javaconnect.getCon();
            stmt=con.createStatement();
        rs=stmt.executeQuery(sql);
        for(;count>0;count--)
            ob.removeRow(0);      
        while(rs.next())
        {
           String bookid, title, author, publication, pages, rating, price, edition, genre;
           bookid=rs.getString("bookid");
           title=rs.getString("name");
           author=rs.getString("author");
           publication=rs.getString("publication");
           pages=rs.getString("pages");
           rating=rs.getString("rating");
           edition=rs.getString("edition");
           price=rs.getString("price");
           genre=rs.getString("genre");
           String x[]={bookid,title,author,publication,genre,pages,rating,price,edition};
           ob.addRow(x);
           count++;
        }  
        con.close();
        stmt.close();
        rs.close();
        }
        catch(Exception e)
        {}
    }//GEN-LAST:event_jCheckBox16ActionPerformed

    private void jCheckBox14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox14ActionPerformed
        String sql="select * from newbook where genre='Childrens'";
        DefaultTableModel ob=(DefaultTableModel)table.getModel();
        try{
            con=javaconnect.getCon();
            stmt=con.createStatement();
            rs=stmt.executeQuery(sql);
            for(;count>0;count--)
            ob.removeRow(0);
            while(rs.next())
            {
                String bookid, title, author, publication, pages, rating, price, edition, genre;
                bookid=rs.getString("bookid");
                title=rs.getString("name");
                author=rs.getString("author");
                publication=rs.getString("publication");
                pages=rs.getString("pages");
                rating=rs.getString("rating");
                edition=rs.getString("edition");
                price=rs.getString("price");
                genre=rs.getString("genre");
                String x[]={bookid,title,author,publication,genre,pages,rating,price,edition};
                ob.addRow(x);
                count++;
            }
            con.close();
            stmt.close();
            rs.close();
        }
        catch(Exception e)
        {}
    }//GEN-LAST:event_jCheckBox14ActionPerformed

    private void langActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_langActionPerformed
        String sql="select * from newbook where language='"+lang.getSelectedItem()+"'";
        DefaultTableModel ob=(DefaultTableModel)table.getModel();
        try{
            con=javaconnect.getCon();
            stmt=con.createStatement();
            rs=stmt.executeQuery(sql);
            for(;count>0;count--)
            ob.removeRow(0);
            while(rs.next())
            {
                String bookid, title, author, publication, pages, rating, price, edition, genre;
                bookid=rs.getString("bookid");
                title=rs.getString("name");
                author=rs.getString("author");
                publication=rs.getString("publication");
                pages=rs.getString("pages");
                rating=rs.getString("rating");
                edition=rs.getString("edition");
                price=rs.getString("price");
                genre=rs.getString("genre");
                String x[]={bookid,title,author,publication,genre,pages,rating,price,edition};
                ob.addRow(x);
                count++;
            }
            con.close();
            stmt.close();
            rs.close();
        }
        catch(Exception e)
        {}// TODO add your handling code here:
    }//GEN-LAST:event_langActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        String keyword=t2.getText();
        String sql="select * from newbook where name like '"+keyword+"%' or author like '"+keyword+"%'";
        DefaultTableModel ob=(DefaultTableModel)table.getModel();
        try{
            con=javaconnect.getCon();
            stmt=con.createStatement();
            rs=stmt.executeQuery(sql);
            for(;count>0;count--)
            ob.removeRow(0);
            while(rs.next())
            {
                String bookid, title, author, publication, pages, rating, price, edition, genre;
                bookid=rs.getString("bookid");
                title=rs.getString("name");
                author=rs.getString("author");
                publication=rs.getString("publication");
                pages=rs.getString("pages");
                rating=rs.getString("rating");
                edition=rs.getString("edition");
                price=rs.getString("price");
                genre=rs.getString("genre");
                String x[]={bookid,title,author,publication,genre,pages,rating,price,edition};
                ob.addRow(x);
                count++;
            }
            con.close();
            stmt.close();
            rs.close();
        }
        catch(Exception e)
        {}// TODO add your handling code here:
    }//GEN-LAST:event_b1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        String keyword=t2.getText();
        String sql="select * from newbook order by name asc";
        DefaultTableModel ob=(DefaultTableModel)table.getModel();
        try{
            con=javaconnect.getCon();
            stmt=con.createStatement();
            rs=stmt.executeQuery(sql);
            for(;count>0;count--)
            ob.removeRow(0);
            while(rs.next())
            {
                String bookid, title, author, publication, pages, rating, price, edition, genre;
                bookid=rs.getString("bookid");
                title=rs.getString("name");
                author=rs.getString("author");
                publication=rs.getString("publication");
                pages=rs.getString("pages");
                rating=rs.getString("rating");
                edition=rs.getString("edition");
                price=rs.getString("price");
                genre=rs.getString("genre");
                String x[]={bookid,title,author,publication,genre,pages,rating,price,edition};
                ob.addRow(x);
                count++;
            }
            jRadioButton1.setSelected(false);
            con.close();
            stmt.close();
            rs.close();
        }
        catch(Exception e)
        {}
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton1ItemStateChanged
        String sql="select * from newbook order by bookid asc";
        DefaultTableModel ob=(DefaultTableModel)table.getModel();

        for(;count>0;count--)
            ob.removeRow(0);
        try{
            con=javaconnect.getCon();
            stmt=con.createStatement();
        rs=stmt.executeQuery(sql);
        while(rs.next())
        {
           String bookid, title, author, publication, pages, rating, price, edition, genre;
           bookid=rs.getString("bookid");
           title=rs.getString("name");
           author=rs.getString("author");
           publication=rs.getString("publication");
           pages=rs.getString("pages");
           rating=rs.getString("rating");
           edition=rs.getString("edition");
           price=rs.getString("price");
           genre=rs.getString("genre");
           String x[]={bookid,title,author,publication,genre,pages,rating,price,edition};
          
           ob.addRow(x);
           count++;
        }  
        //System.out.print(count);
        jRadioButton2.setSelected(false);
        con.close();
        stmt.close();
        rs.close();
        }
        catch(Exception e){}// TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cb1;
    public javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> lang;
    public javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
